# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

# source 'https://github.com/CocoaPods/Specs.git'
target 'KkListActionSheetSwiftDemo' do
 pod 'KkListActionSheet-Swift'
end

target 'KkListActionSheetSwiftDemoTests' do
  pod 'KkListActionSheet-Swift'
end
