# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'KkListActionSheet-SwiftDemo' do
 pod 'KkListActionSheet-Swift', :path=>'../'
end

target 'KkListActionSheet-SwiftDemoTests' do

end

target 'KkListActionSheet-SwiftDemoUITests' do

end
